[template]
src = "site.cert.tmpl"
dest = "/etc/traefik/site.cert"
prefix = "/%%STACK%%/%%ENVIRONMENT%%"

uid = 0
gid = 0
mode = "0640"

keys = [
    "/config/*",
    "/config"
]

reload_cmd = "/sbin/reload traefik || /sbin/restart traefik || /sbin/start traefik"
